env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
plugins:
  - react
  - '@typescript-eslint'
rules: {
  "linebreak-style": 0,
  "eslint linebreak-style": [0, "error", "windows"],
  "max-len": ["error", { "ignoreComments": true, "code": 120 }],
}
